<h1 class="text-primary">Album</h1>

<p>
    <a href="<?= $this->url('images', ['action'=>'upload']); ?>" class="btn btn-primary" role="button">Upload</a>
</p>

<hr/>

<?php if(count($files)==0): ?>
<p>
    <i>There are no files to display.</i>
</p>
<?php else: ?>
<div class="row">
    <?php foreach($files as $file): ?>  
        <div class="col-6 col-sm-4 col-lg-3">
            <div class="card mb-2">
                <img src="<?= $this->url('images', ['action'=>'file'], ['query'=>['name'=>$file]]); ?>">
                <div class="card-body">
                    <h5 class="card-title"><?php echo $file; ?></h5>
                    <a href="<?= $this->url('images', ['action'=>'delete'], ['query'=>['name'=>$file]]); ?>" class="btn btn-danger">Remove</a>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>
<?php endif; ?>